//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keszlet
    {
        public int Id { get; set; }
        public int Mennyiseg { get; set; }
    
        public virtual Szeriaszamok Szeriaszamok { get; set; }
        public virtual Termekek Termekek { get; set; }
        public virtual Polcok Polcok { get; set; }
    }
}
