//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szeriaszamok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szeriaszamok()
        {
            this.Keszlet = new HashSet<Keszlet>();
        }
    
        public int Id { get; set; }
        public string Szeriaszam { get; set; }
        public string Statusz { get; set; }
    
        public virtual Termekek Termekek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keszlet> Keszlet { get; set; }
    }
}
